### ISSUE TITLE
Determine use of query-string vs node.js query string

### ISSUE THREAD

**Issue by mjoyce91** [18F/State-TalentMAP#410]
Determine whether to use [query-string](https://github.com/sindresorhus/query-string) or [node.js querystring](https://nodejs.org/api/querystring.html) and change front-end if needed.

**Comment by mjoyce91** [comment]
Use of `querystring` is fine, but getting the following error in tests:

```
Summary of all failing tests
 FAIL  src/Components/Filters/Filters.test.jsx (7.037s)
  ● FiltersComponent › can call the createQueryString function to create multi-parameter query strings

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
      
      at pTimeout (node_modules/jest-jasmine2/build/queueRunner.js:53:21)
      at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:523:19)
      at ontimeout (timers.js:365:14)
      at tryOnTimeout (timers.js:237:5)
      at Timer.listOnTimeout (timers.js:207:5)
```

**Comment by jseppi** [comment]
If it's causing issues, I wouldn't spend too much time on it. The lib you're using already is also well tested and used by lots of projects.
